version: '2'

services:
  elasticsearch:
    image: elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
#      - vm.max_map_count=262144
    volumes:
      - $PWD/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    volumes:
      - $PWD/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5005:5000"
    links:
      - elasticsearch

  kibana:
    image: kibana:7.1.1
#    build: kibana/
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  filebeat-nginx:
    image: docker.elastic.co/beats/filebeat:7.1.1
    volumes:
      - /home/zrhm7232/MyFiles/Projects/omid/omid2/openresty/log/access.log:/logs/omid2/openresty/access.log
#      - /home/zrhm7232/MyFiles/Projects/omid/omid2/python_mm/log/debug:/logs/omid2/mm/debug
      - "$PWD/filebeat/config/nginx.yml:/usr/share/filebeat/filebeat.yml:ro"

  filebeat-mm:
    image: docker.elastic.co/beats/filebeat:7.1.1
    volumes:
#      - /home/zrhm7232/MyFiles/Projects/omid/omid2/openresty/log/access.log:/logs/omid2/openresty/access.log
#      - /home/zrhm7232/MyFiles/Projects/omid/omid2/python_mm/log/debug:/logs/omid2/mm/debug
      - "$PWD/filebeat/config/mm.yml:/usr/share/filebeat/filebeat.yml:ro"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.1.1
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
#      - $PWD:/hostfs:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro