version: '2'

services:
  elasticsearch:
    image: elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    volumes:
      - $PWD/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5005:5000"
    links:
      - elasticsearch

  kibana:
    image: kibana:7.1.1
#    build: kibana/
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.1.1
    volumes:
      - /home/zrhm7232/MyFiles/Projects/omid/omid2/openresty/log/access.log:/logs/omid2/openresty/access.log
      - "$PWD/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"